# Generated by Django 3.2.8 on 2021-10-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectInfo',
        ),
    ]
